export const races = [
    'Aarakocra',
    'Aasimar',
    'Aven',
    'Bugbear',
    'Bullywug',
    'Centaur',
    'Changeling',
    'Dragonborn',
    'Dwarf',
    'Elf',
    'Firbolg',
    'Genasi',
    'Gith',
    'Gnoll',
    'Gnome',
    'Deep Gnome',
    'Goblin',
    'Goliath',
    'Half-Elf',
    'Halfling',
    'Half-Orc',
    'Hobgoblin',
    'Human',
    'Kenku',
    'Kobold',
    'Leonin',
    'Lizardfolk',
    'Loxodon',
    'Merfolk',
    'Minotaur',
    'Naga',
    'Orc',
    'Satyr',
    'Shifter',
    'Simic Hybrid',
    [0.1, 'Skeleton'],
    'Tabaxi',
    'Tiefling',
    'Tortle',
    'Triton',
    'Warforged',
    'Yuan-ti Pureblood',
    [0.1, 'Zombie'],
    'Man-Horse',
    [0.1, '2 Gnomes in a trench coat'],
    [0.1, '2 Kobolds in a trench coat'],
    [0.1, '2 Halflings in a trench coat'],
] as const
